import { MessagesContext } from "@/context/MessagesContextProvider";
import {
	PageLoadingContext,
	PageLoadingContextInterface,
} from "@/context/PageLoadingProvider";
import Head from "next/head";
import { ReactNode, useContext, useEffect, useState } from "react";
import { NavbarContainer } from "../../containers/NavbarContainer/NavbarContainer";
import { PageLoadingComponent } from "../PageLoadingComponent/PageLoadingComponent";
import style from "./Layout.module.scss";

export default function Layout({
	children,
	messages,
}: {
	children: ReactNode;
	messages: any;
}) {
	const { setActiveMessages } = useContext(MessagesContext) as {
		setActiveMessages: Function;
	};
	const { pageLoading, setPageLoading } = useContext(
		PageLoadingContext
	) as PageLoadingContextInterface;

	useEffect(() => {
		setActiveMessages(messages);
	}, [messages]);

	useEffect(() => {
		setTimeout(() => {
			console.log("EJECUTANDO");
			setPageLoading && setPageLoading(false);
		}, 300);
	}, [messages]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavbarContainer />
			<main className={style["main-content"]}>{children}</main>
			<PageLoadingComponent pageLoading={pageLoading} />
		</>
	);
}
