import { MessagesContext } from "@/context/messagesContextProvider";
import Head from "next/head";
import { ReactNode, useContext, useEffect } from "react";
import { NavbarContainer } from "../../containers/NavbarContainer/NavbarContainer";

export default function Layout({
	children,
	messages,
}: {
	children: ReactNode;
	messages: any;
}) {
	const { setActiveMessages } = useContext(MessagesContext) as {
		setActiveMessages: Function;
	};
	useEffect(() => {
		setActiveMessages(messages);
	}, [messages]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavbarContainer />
			<main>{children}</main>
		</>
	);
}
